export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_CONTACTS_PENDING = 'REQUEST_CONTACTS_PENDING';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS';
export const REQUEST_CONTACTS_FAILED = 'REQUEST_CONTACTS_FAILED';

export const REQUEST_CONTACT_PENDING = 'REQUEST_CONTACT_PENDING';
export const REQUEST_CONTACT_SUCCESS = 'REQUEST_CONTACT_SUCCESS';
export const REQUEST_CONTACT_FAILED = 'REQUEST_CONTACT_FAILED';